// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s (
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        p_read16,
        p_read17,
        p_read18,
        p_read19,
        p_read20,
        p_read21,
        p_read22,
        p_read23,
        p_read24,
        p_read25,
        p_read26,
        p_read27,
        p_read28,
        ap_return
);


output   ap_ready;
input  [15:0] p_read;
input  [15:0] p_read1;
input  [15:0] p_read2;
input  [15:0] p_read3;
input  [15:0] p_read4;
input  [15:0] p_read5;
input  [15:0] p_read6;
input  [15:0] p_read7;
input  [15:0] p_read8;
input  [15:0] p_read9;
input  [15:0] p_read10;
input  [15:0] p_read11;
input  [15:0] p_read12;
input  [15:0] p_read13;
input  [15:0] p_read14;
input  [15:0] p_read15;
input  [15:0] p_read16;
input  [15:0] p_read17;
input  [15:0] p_read18;
input  [15:0] p_read19;
input  [15:0] p_read20;
input  [15:0] p_read21;
input  [15:0] p_read22;
input  [15:0] p_read23;
input  [15:0] p_read24;
input  [15:0] p_read25;
input  [15:0] p_read26;
input  [15:0] p_read27;
input  [15:0] p_read28;
output  [15:0] ap_return;

wire  signed [15:0] sext_ln70_fu_298_p0;
wire  signed [15:0] shl_ln_fu_302_p1;
wire   [17:0] shl_ln_fu_302_p3;
wire  signed [18:0] sext_ln1319_fu_310_p1;
wire   [18:0] sub_ln1319_fu_314_p2;
wire  signed [18:0] sext_ln70_fu_298_p1;
wire   [18:0] r_V_fu_320_p2;
wire   [13:0] mult_V_fu_326_p4;
wire  signed [16:0] sext_ln70_1_fu_340_p1;
wire   [16:0] r_V_1_fu_344_p2;
wire   [11:0] mult_V_1_fu_350_p4;
wire   [17:0] shl_ln1319_1_fu_364_p3;
wire  signed [18:0] sext_ln1319_1_fu_372_p1;
wire   [18:0] r_V_2_fu_376_p2;
wire   [13:0] mult_V_2_fu_382_p4;
wire  signed [15:0] sext_ln70_2_fu_396_p0;
wire  signed [15:0] shl_ln1319_2_fu_400_p1;
wire   [17:0] shl_ln1319_2_fu_400_p3;
wire  signed [18:0] sext_ln1319_2_fu_408_p1;
wire   [18:0] sub_ln1319_4_fu_412_p2;
wire  signed [18:0] sext_ln70_2_fu_396_p1;
wire   [18:0] r_V_3_fu_418_p2;
wire   [13:0] mult_V_3_fu_424_p4;
wire  signed [15:0] sext_ln70_3_fu_438_p0;
wire  signed [15:0] shl_ln1319_3_fu_442_p1;
wire   [17:0] shl_ln1319_3_fu_442_p3;
wire  signed [18:0] sext_ln1319_3_fu_450_p1;
wire   [18:0] sub_ln1319_6_fu_454_p2;
wire  signed [18:0] sext_ln70_3_fu_438_p1;
wire   [18:0] r_V_4_fu_460_p2;
wire   [13:0] mult_V_4_fu_466_p4;
wire   [16:0] shl_ln1319_4_fu_480_p3;
wire  signed [17:0] sext_ln1319_4_fu_488_p1;
wire   [17:0] r_V_5_fu_492_p2;
wire   [12:0] mult_V_5_fu_498_p4;
wire   [18:0] shl_ln1319_5_fu_512_p3;
wire   [16:0] shl_ln1319_6_fu_524_p3;
wire  signed [19:0] sext_ln1319_5_fu_520_p1;
wire  signed [19:0] sext_ln1319_6_fu_532_p1;
wire   [19:0] r_V_6_fu_536_p2;
wire   [14:0] mult_V_6_fu_542_p4;
wire   [11:0] mult_V_7_fu_556_p4;
wire   [12:0] mult_V_8_fu_570_p4;
wire  signed [15:0] sext_ln70_4_fu_584_p0;
wire  signed [15:0] shl_ln1319_7_fu_588_p1;
wire   [17:0] shl_ln1319_7_fu_588_p3;
wire  signed [18:0] sext_ln1319_7_fu_596_p1;
wire  signed [18:0] sext_ln70_4_fu_584_p1;
wire   [18:0] r_V_7_fu_600_p2;
wire   [13:0] mult_V_9_fu_606_p4;
wire  signed [15:0] sext_ln70_5_fu_620_p0;
wire  signed [15:0] shl_ln1319_8_fu_624_p1;
wire   [18:0] shl_ln1319_8_fu_624_p3;
wire  signed [19:0] sext_ln1319_8_fu_632_p1;
wire  signed [19:0] sext_ln70_5_fu_620_p1;
wire   [19:0] r_V_8_fu_636_p2;
wire   [14:0] mult_V_10_fu_642_p4;
wire  signed [15:0] sext_ln70_6_fu_656_p0;
wire  signed [15:0] shl_ln1319_9_fu_660_p1;
wire   [17:0] shl_ln1319_9_fu_660_p3;
wire  signed [18:0] sext_ln1319_9_fu_668_p1;
wire  signed [18:0] sext_ln70_6_fu_656_p1;
wire   [18:0] r_V_9_fu_672_p2;
wire   [13:0] mult_V_11_fu_678_p4;
wire   [18:0] shl_ln1319_s_fu_692_p3;
wire  signed [19:0] sext_ln1319_10_fu_700_p1;
wire   [19:0] r_V_10_fu_704_p2;
wire   [14:0] mult_V_12_fu_710_p4;
wire   [18:0] shl_ln1319_10_fu_724_p3;
wire   [16:0] shl_ln1319_11_fu_736_p3;
wire  signed [19:0] sext_ln1319_11_fu_732_p1;
wire  signed [19:0] sext_ln1319_12_fu_744_p1;
wire   [19:0] r_V_11_fu_748_p2;
wire   [14:0] mult_V_13_fu_754_p4;
wire  signed [15:0] sext_ln70_7_fu_768_p0;
wire  signed [15:0] shl_ln1319_12_fu_772_p1;
wire   [17:0] shl_ln1319_12_fu_772_p3;
wire  signed [18:0] sext_ln1319_13_fu_780_p1;
wire   [18:0] sub_ln1319_14_fu_784_p2;
wire  signed [18:0] sext_ln70_7_fu_768_p1;
wire   [18:0] r_V_12_fu_790_p2;
wire   [13:0] mult_V_14_fu_796_p4;
wire  signed [15:0] sext_ln70_8_fu_810_p0;
wire  signed [15:0] shl_ln1319_13_fu_814_p1;
wire   [18:0] shl_ln1319_13_fu_814_p3;
wire  signed [19:0] sext_ln1319_14_fu_822_p1;
wire  signed [19:0] sext_ln70_8_fu_810_p1;
wire   [19:0] r_V_13_fu_826_p2;
wire   [14:0] mult_V_15_fu_832_p4;
wire  signed [15:0] sext_ln70_9_fu_846_p0;
wire  signed [15:0] shl_ln1319_14_fu_850_p1;
wire   [17:0] shl_ln1319_14_fu_850_p3;
wire  signed [18:0] sext_ln1319_15_fu_858_p1;
wire  signed [18:0] sext_ln70_9_fu_846_p1;
wire   [18:0] r_V_14_fu_862_p2;
wire   [13:0] mult_V_16_fu_868_p4;
wire  signed [15:0] sext_ln70_10_fu_882_p0;
wire  signed [15:0] shl_ln1319_15_fu_886_p1;
wire   [18:0] shl_ln1319_15_fu_886_p3;
wire  signed [19:0] sext_ln1319_16_fu_894_p1;
wire  signed [19:0] sext_ln70_10_fu_882_p1;
wire   [19:0] r_V_15_fu_898_p2;
wire   [14:0] mult_V_17_fu_904_p4;
wire  signed [15:0] sext_ln70_11_fu_918_p0;
wire  signed [15:0] shl_ln1319_16_fu_922_p1;
wire   [17:0] shl_ln1319_16_fu_922_p3;
wire  signed [18:0] sext_ln1319_17_fu_930_p1;
wire  signed [18:0] sext_ln70_11_fu_918_p1;
wire   [18:0] r_V_16_fu_934_p2;
wire   [13:0] mult_V_18_fu_940_p4;
wire   [18:0] shl_ln1319_17_fu_954_p3;
wire   [16:0] shl_ln1319_18_fu_966_p3;
wire  signed [19:0] sext_ln1319_18_fu_962_p1;
wire  signed [19:0] sext_ln1319_19_fu_974_p1;
wire   [19:0] r_V_17_fu_978_p2;
wire   [14:0] mult_V_19_fu_984_p4;
wire   [10:0] mult_V_20_fu_998_p4;
wire  signed [15:0] sext_ln70_12_fu_1012_p0;
wire  signed [15:0] shl_ln1319_19_fu_1016_p1;
wire   [18:0] shl_ln1319_19_fu_1016_p3;
wire  signed [19:0] sext_ln1319_20_fu_1024_p1;
wire  signed [19:0] sext_ln70_12_fu_1012_p1;
wire   [19:0] r_V_18_fu_1028_p2;
wire   [14:0] mult_V_21_fu_1034_p4;
wire  signed [15:0] sext_ln70_13_fu_1048_p0;
wire  signed [15:0] shl_ln1319_20_fu_1052_p1;
wire   [17:0] shl_ln1319_20_fu_1052_p3;
wire  signed [18:0] sext_ln1319_21_fu_1060_p1;
wire  signed [18:0] sext_ln70_13_fu_1048_p1;
wire   [18:0] r_V_19_fu_1064_p2;
wire   [13:0] mult_V_22_fu_1070_p4;
wire  signed [15:0] sext_ln70_14_fu_1084_p0;
wire  signed [15:0] shl_ln1319_21_fu_1088_p1;
wire   [17:0] shl_ln1319_21_fu_1088_p3;
wire  signed [18:0] sext_ln1319_22_fu_1096_p1;
wire   [18:0] sub_ln1319_21_fu_1100_p2;
wire  signed [18:0] sext_ln70_14_fu_1084_p1;
wire   [18:0] r_V_20_fu_1106_p2;
wire   [13:0] mult_V_23_fu_1112_p4;
wire   [16:0] shl_ln1319_22_fu_1126_p3;
wire  signed [17:0] sext_ln1319_23_fu_1134_p1;
wire   [17:0] r_V_21_fu_1138_p2;
wire   [12:0] mult_V_24_fu_1144_p4;
wire   [18:0] shl_ln1319_23_fu_1158_p3;
wire   [16:0] shl_ln1319_24_fu_1170_p3;
wire  signed [19:0] sext_ln1319_25_fu_1178_p1;
wire  signed [19:0] sext_ln1319_24_fu_1166_p1;
wire   [19:0] r_V_22_fu_1182_p2;
wire   [14:0] mult_V_25_fu_1188_p4;
wire  signed [15:0] sext_ln70_15_fu_1202_p0;
wire  signed [15:0] shl_ln1319_25_fu_1206_p1;
wire   [18:0] shl_ln1319_25_fu_1206_p3;
wire  signed [19:0] sext_ln1319_26_fu_1214_p1;
wire  signed [19:0] sext_ln70_15_fu_1202_p1;
wire   [19:0] r_V_23_fu_1218_p2;
wire   [14:0] mult_V_26_fu_1224_p4;
wire  signed [15:0] sext_ln70_16_fu_1238_p0;
wire  signed [15:0] shl_ln1319_26_fu_1242_p1;
wire   [18:0] shl_ln1319_26_fu_1242_p3;
wire  signed [19:0] sext_ln1319_27_fu_1250_p1;
wire  signed [19:0] sext_ln70_16_fu_1238_p1;
wire   [19:0] r_V_24_fu_1254_p2;
wire   [14:0] mult_V_27_fu_1260_p4;
wire   [18:0] shl_ln1319_27_fu_1274_p3;
wire   [16:0] shl_ln1319_28_fu_1286_p3;
wire  signed [19:0] sext_ln1319_29_fu_1294_p1;
wire  signed [19:0] sext_ln1319_28_fu_1282_p1;
wire   [19:0] r_V_25_fu_1298_p2;
wire   [14:0] mult_V_28_fu_1304_p4;
wire  signed [14:0] sext_ln17_2_fu_360_p1;
wire  signed [14:0] sext_ln17_3_fu_392_p1;
wire   [14:0] add_ln859_fu_1318_p2;
wire  signed [15:0] sext_ln859_1_fu_1324_p1;
wire  signed [15:0] sext_ln864_1_fu_336_p1;
wire  signed [14:0] sext_ln17_4_fu_434_p1;
wire  signed [14:0] sext_ln17_5_fu_476_p1;
wire   [14:0] add_ln859_2_fu_1334_p2;
wire  signed [15:0] sext_ln864_2_fu_508_p1;
wire  signed [15:0] sext_ln864_3_fu_552_p1;
wire   [15:0] add_ln859_3_fu_1344_p2;
wire  signed [15:0] sext_ln859_2_fu_1340_p1;
wire   [15:0] add_ln859_4_fu_1350_p2;
wire   [15:0] add_ln859_1_fu_1328_p2;
wire  signed [15:0] sext_ln864_5_fu_652_p1;
wire  signed [15:0] sext_ln864_6_fu_688_p1;
wire   [15:0] add_ln859_6_fu_1362_p2;
wire  signed [15:0] sext_ln864_4_fu_616_p1;
wire  signed [15:0] sext_ln864_7_fu_720_p1;
wire  signed [15:0] sext_ln864_8_fu_764_p1;
wire  signed [15:0] sext_ln864_9_fu_806_p1;
wire  signed [15:0] sext_ln864_10_fu_842_p1;
wire   [15:0] add_ln859_9_fu_1380_p2;
wire   [15:0] add_ln859_8_fu_1374_p2;
wire   [15:0] add_ln859_10_fu_1386_p2;
wire   [15:0] add_ln859_7_fu_1368_p2;
wire   [15:0] add_ln859_11_fu_1392_p2;
wire   [15:0] add_ln859_5_fu_1356_p2;
wire  signed [15:0] sext_ln864_12_fu_914_p1;
wire  signed [15:0] sext_ln864_13_fu_950_p1;
wire   [15:0] add_ln859_13_fu_1404_p2;
wire  signed [15:0] sext_ln864_11_fu_878_p1;
wire  signed [15:0] sext_ln864_14_fu_994_p1;
wire  signed [15:0] sext_ln864_15_fu_1044_p1;
wire  signed [14:0] sext_ln17_6_fu_1080_p1;
wire  signed [14:0] sext_ln17_7_fu_1122_p1;
wire   [14:0] add_ln859_16_fu_1422_p2;
wire  signed [15:0] sext_ln859_3_fu_1428_p1;
wire   [15:0] add_ln859_15_fu_1416_p2;
wire   [15:0] add_ln859_17_fu_1432_p2;
wire   [15:0] add_ln859_14_fu_1410_p2;
wire  signed [15:0] sext_ln864_16_fu_1154_p1;
wire  signed [15:0] sext_ln864_17_fu_1198_p1;
wire  signed [15:0] sext_ln864_18_fu_1234_p1;
wire  signed [15:0] sext_ln864_19_fu_1270_p1;
wire   [15:0] add_ln859_20_fu_1450_p2;
wire   [15:0] add_ln859_19_fu_1444_p2;
wire  signed [15:0] sext_ln864_20_fu_1314_p1;
wire  signed [15:0] sext_ln864_fu_580_p1;
wire  signed [12:0] sext_ln17_fu_566_p1;
wire  signed [12:0] sext_ln17_1_fu_1008_p1;
wire   [12:0] add_ln859_23_fu_1468_p2;
wire  signed [15:0] sext_ln859_fu_1474_p1;
wire   [15:0] add_ln859_22_fu_1462_p2;
wire   [15:0] add_ln859_24_fu_1478_p2;
wire   [15:0] add_ln859_21_fu_1456_p2;
wire   [15:0] add_ln859_25_fu_1484_p2;
wire   [15:0] add_ln859_18_fu_1438_p2;
wire   [15:0] add_ln859_26_fu_1490_p2;
wire   [15:0] add_ln859_12_fu_1398_p2;

assign add_ln859_10_fu_1386_p2 = (add_ln859_9_fu_1380_p2 + add_ln859_8_fu_1374_p2);

assign add_ln859_11_fu_1392_p2 = (add_ln859_10_fu_1386_p2 + add_ln859_7_fu_1368_p2);

assign add_ln859_12_fu_1398_p2 = (add_ln859_11_fu_1392_p2 + add_ln859_5_fu_1356_p2);

assign add_ln859_13_fu_1404_p2 = ($signed(sext_ln864_12_fu_914_p1) + $signed(sext_ln864_13_fu_950_p1));

assign add_ln859_14_fu_1410_p2 = ($signed(add_ln859_13_fu_1404_p2) + $signed(sext_ln864_11_fu_878_p1));

assign add_ln859_15_fu_1416_p2 = ($signed(sext_ln864_14_fu_994_p1) + $signed(sext_ln864_15_fu_1044_p1));

assign add_ln859_16_fu_1422_p2 = ($signed(sext_ln17_6_fu_1080_p1) + $signed(sext_ln17_7_fu_1122_p1));

assign add_ln859_17_fu_1432_p2 = ($signed(sext_ln859_3_fu_1428_p1) + $signed(add_ln859_15_fu_1416_p2));

assign add_ln859_18_fu_1438_p2 = (add_ln859_17_fu_1432_p2 + add_ln859_14_fu_1410_p2);

assign add_ln859_19_fu_1444_p2 = ($signed(sext_ln864_16_fu_1154_p1) + $signed(sext_ln864_17_fu_1198_p1));

assign add_ln859_1_fu_1328_p2 = ($signed(sext_ln859_1_fu_1324_p1) + $signed(sext_ln864_1_fu_336_p1));

assign add_ln859_20_fu_1450_p2 = ($signed(sext_ln864_18_fu_1234_p1) + $signed(sext_ln864_19_fu_1270_p1));

assign add_ln859_21_fu_1456_p2 = (add_ln859_20_fu_1450_p2 + add_ln859_19_fu_1444_p2);

assign add_ln859_22_fu_1462_p2 = ($signed(sext_ln864_20_fu_1314_p1) + $signed(sext_ln864_fu_580_p1));

assign add_ln859_23_fu_1468_p2 = ($signed(sext_ln17_fu_566_p1) + $signed(sext_ln17_1_fu_1008_p1));

assign add_ln859_24_fu_1478_p2 = ($signed(sext_ln859_fu_1474_p1) + $signed(add_ln859_22_fu_1462_p2));

assign add_ln859_25_fu_1484_p2 = (add_ln859_24_fu_1478_p2 + add_ln859_21_fu_1456_p2);

assign add_ln859_26_fu_1490_p2 = (add_ln859_25_fu_1484_p2 + add_ln859_18_fu_1438_p2);

assign add_ln859_2_fu_1334_p2 = ($signed(sext_ln17_4_fu_434_p1) + $signed(sext_ln17_5_fu_476_p1));

assign add_ln859_3_fu_1344_p2 = ($signed(sext_ln864_2_fu_508_p1) + $signed(sext_ln864_3_fu_552_p1));

assign add_ln859_4_fu_1350_p2 = ($signed(add_ln859_3_fu_1344_p2) + $signed(sext_ln859_2_fu_1340_p1));

assign add_ln859_5_fu_1356_p2 = (add_ln859_4_fu_1350_p2 + add_ln859_1_fu_1328_p2);

assign add_ln859_6_fu_1362_p2 = ($signed(sext_ln864_5_fu_652_p1) + $signed(sext_ln864_6_fu_688_p1));

assign add_ln859_7_fu_1368_p2 = ($signed(add_ln859_6_fu_1362_p2) + $signed(sext_ln864_4_fu_616_p1));

assign add_ln859_8_fu_1374_p2 = ($signed(sext_ln864_7_fu_720_p1) + $signed(sext_ln864_8_fu_764_p1));

assign add_ln859_9_fu_1380_p2 = ($signed(sext_ln864_9_fu_806_p1) + $signed(sext_ln864_10_fu_842_p1));

assign add_ln859_fu_1318_p2 = ($signed(sext_ln17_2_fu_360_p1) + $signed(sext_ln17_3_fu_392_p1));

assign ap_ready = 1'b1;

assign ap_return = (add_ln859_26_fu_1490_p2 + add_ln859_12_fu_1398_p2);

assign mult_V_10_fu_642_p4 = {{r_V_8_fu_636_p2[19:5]}};

assign mult_V_11_fu_678_p4 = {{r_V_9_fu_672_p2[18:5]}};

assign mult_V_12_fu_710_p4 = {{r_V_10_fu_704_p2[19:5]}};

assign mult_V_13_fu_754_p4 = {{r_V_11_fu_748_p2[19:5]}};

assign mult_V_14_fu_796_p4 = {{r_V_12_fu_790_p2[18:5]}};

assign mult_V_15_fu_832_p4 = {{r_V_13_fu_826_p2[19:5]}};

assign mult_V_16_fu_868_p4 = {{r_V_14_fu_862_p2[18:5]}};

assign mult_V_17_fu_904_p4 = {{r_V_15_fu_898_p2[19:5]}};

assign mult_V_18_fu_940_p4 = {{r_V_16_fu_934_p2[18:5]}};

assign mult_V_19_fu_984_p4 = {{r_V_17_fu_978_p2[19:5]}};

assign mult_V_1_fu_350_p4 = {{r_V_1_fu_344_p2[16:5]}};

assign mult_V_20_fu_998_p4 = {{p_read20[15:5]}};

assign mult_V_21_fu_1034_p4 = {{r_V_18_fu_1028_p2[19:5]}};

assign mult_V_22_fu_1070_p4 = {{r_V_19_fu_1064_p2[18:5]}};

assign mult_V_23_fu_1112_p4 = {{r_V_20_fu_1106_p2[18:5]}};

assign mult_V_24_fu_1144_p4 = {{r_V_21_fu_1138_p2[17:5]}};

assign mult_V_25_fu_1188_p4 = {{r_V_22_fu_1182_p2[19:5]}};

assign mult_V_26_fu_1224_p4 = {{r_V_23_fu_1218_p2[19:5]}};

assign mult_V_27_fu_1260_p4 = {{r_V_24_fu_1254_p2[19:5]}};

assign mult_V_28_fu_1304_p4 = {{r_V_25_fu_1298_p2[19:5]}};

assign mult_V_2_fu_382_p4 = {{r_V_2_fu_376_p2[18:5]}};

assign mult_V_3_fu_424_p4 = {{r_V_3_fu_418_p2[18:5]}};

assign mult_V_4_fu_466_p4 = {{r_V_4_fu_460_p2[18:5]}};

assign mult_V_5_fu_498_p4 = {{r_V_5_fu_492_p2[17:5]}};

assign mult_V_6_fu_542_p4 = {{r_V_6_fu_536_p2[19:5]}};

assign mult_V_7_fu_556_p4 = {{p_read7[15:4]}};

assign mult_V_8_fu_570_p4 = {{p_read8[15:3]}};

assign mult_V_9_fu_606_p4 = {{r_V_7_fu_600_p2[18:5]}};

assign mult_V_fu_326_p4 = {{r_V_fu_320_p2[18:5]}};

assign r_V_10_fu_704_p2 = ($signed(20'd0) - $signed(sext_ln1319_10_fu_700_p1));

assign r_V_11_fu_748_p2 = ($signed(sext_ln1319_11_fu_732_p1) - $signed(sext_ln1319_12_fu_744_p1));

assign r_V_12_fu_790_p2 = ($signed(sub_ln1319_14_fu_784_p2) - $signed(sext_ln70_7_fu_768_p1));

assign r_V_13_fu_826_p2 = ($signed(sext_ln1319_14_fu_822_p1) + $signed(sext_ln70_8_fu_810_p1));

assign r_V_14_fu_862_p2 = ($signed(sext_ln1319_15_fu_858_p1) + $signed(sext_ln70_9_fu_846_p1));

assign r_V_15_fu_898_p2 = ($signed(sext_ln1319_16_fu_894_p1) - $signed(sext_ln70_10_fu_882_p1));

assign r_V_16_fu_934_p2 = ($signed(sext_ln1319_17_fu_930_p1) - $signed(sext_ln70_11_fu_918_p1));

assign r_V_17_fu_978_p2 = ($signed(sext_ln1319_18_fu_962_p1) - $signed(sext_ln1319_19_fu_974_p1));

assign r_V_18_fu_1028_p2 = ($signed(sext_ln1319_20_fu_1024_p1) - $signed(sext_ln70_12_fu_1012_p1));

assign r_V_19_fu_1064_p2 = ($signed(sext_ln1319_21_fu_1060_p1) - $signed(sext_ln70_13_fu_1048_p1));

assign r_V_1_fu_344_p2 = ($signed(17'd0) - $signed(sext_ln70_1_fu_340_p1));

assign r_V_20_fu_1106_p2 = ($signed(sub_ln1319_21_fu_1100_p2) - $signed(sext_ln70_14_fu_1084_p1));

assign r_V_21_fu_1138_p2 = ($signed(18'd0) - $signed(sext_ln1319_23_fu_1134_p1));

assign r_V_22_fu_1182_p2 = ($signed(sext_ln1319_25_fu_1178_p1) - $signed(sext_ln1319_24_fu_1166_p1));

assign r_V_23_fu_1218_p2 = ($signed(sext_ln1319_26_fu_1214_p1) + $signed(sext_ln70_15_fu_1202_p1));

assign r_V_24_fu_1254_p2 = ($signed(sext_ln1319_27_fu_1250_p1) - $signed(sext_ln70_16_fu_1238_p1));

assign r_V_25_fu_1298_p2 = ($signed(sext_ln1319_29_fu_1294_p1) - $signed(sext_ln1319_28_fu_1282_p1));

assign r_V_2_fu_376_p2 = ($signed(19'd0) - $signed(sext_ln1319_1_fu_372_p1));

assign r_V_3_fu_418_p2 = ($signed(sub_ln1319_4_fu_412_p2) - $signed(sext_ln70_2_fu_396_p1));

assign r_V_4_fu_460_p2 = ($signed(sub_ln1319_6_fu_454_p2) - $signed(sext_ln70_3_fu_438_p1));

assign r_V_5_fu_492_p2 = ($signed(18'd0) - $signed(sext_ln1319_4_fu_488_p1));

assign r_V_6_fu_536_p2 = ($signed(sext_ln1319_5_fu_520_p1) + $signed(sext_ln1319_6_fu_532_p1));

assign r_V_7_fu_600_p2 = ($signed(sext_ln1319_7_fu_596_p1) - $signed(sext_ln70_4_fu_584_p1));

assign r_V_8_fu_636_p2 = ($signed(sext_ln1319_8_fu_632_p1) - $signed(sext_ln70_5_fu_620_p1));

assign r_V_9_fu_672_p2 = ($signed(sext_ln1319_9_fu_668_p1) - $signed(sext_ln70_6_fu_656_p1));

assign r_V_fu_320_p2 = ($signed(sub_ln1319_fu_314_p2) - $signed(sext_ln70_fu_298_p1));

assign sext_ln1319_10_fu_700_p1 = $signed(shl_ln1319_s_fu_692_p3);

assign sext_ln1319_11_fu_732_p1 = $signed(shl_ln1319_10_fu_724_p3);

assign sext_ln1319_12_fu_744_p1 = $signed(shl_ln1319_11_fu_736_p3);

assign sext_ln1319_13_fu_780_p1 = $signed(shl_ln1319_12_fu_772_p3);

assign sext_ln1319_14_fu_822_p1 = $signed(shl_ln1319_13_fu_814_p3);

assign sext_ln1319_15_fu_858_p1 = $signed(shl_ln1319_14_fu_850_p3);

assign sext_ln1319_16_fu_894_p1 = $signed(shl_ln1319_15_fu_886_p3);

assign sext_ln1319_17_fu_930_p1 = $signed(shl_ln1319_16_fu_922_p3);

assign sext_ln1319_18_fu_962_p1 = $signed(shl_ln1319_17_fu_954_p3);

assign sext_ln1319_19_fu_974_p1 = $signed(shl_ln1319_18_fu_966_p3);

assign sext_ln1319_1_fu_372_p1 = $signed(shl_ln1319_1_fu_364_p3);

assign sext_ln1319_20_fu_1024_p1 = $signed(shl_ln1319_19_fu_1016_p3);

assign sext_ln1319_21_fu_1060_p1 = $signed(shl_ln1319_20_fu_1052_p3);

assign sext_ln1319_22_fu_1096_p1 = $signed(shl_ln1319_21_fu_1088_p3);

assign sext_ln1319_23_fu_1134_p1 = $signed(shl_ln1319_22_fu_1126_p3);

assign sext_ln1319_24_fu_1166_p1 = $signed(shl_ln1319_23_fu_1158_p3);

assign sext_ln1319_25_fu_1178_p1 = $signed(shl_ln1319_24_fu_1170_p3);

assign sext_ln1319_26_fu_1214_p1 = $signed(shl_ln1319_25_fu_1206_p3);

assign sext_ln1319_27_fu_1250_p1 = $signed(shl_ln1319_26_fu_1242_p3);

assign sext_ln1319_28_fu_1282_p1 = $signed(shl_ln1319_27_fu_1274_p3);

assign sext_ln1319_29_fu_1294_p1 = $signed(shl_ln1319_28_fu_1286_p3);

assign sext_ln1319_2_fu_408_p1 = $signed(shl_ln1319_2_fu_400_p3);

assign sext_ln1319_3_fu_450_p1 = $signed(shl_ln1319_3_fu_442_p3);

assign sext_ln1319_4_fu_488_p1 = $signed(shl_ln1319_4_fu_480_p3);

assign sext_ln1319_5_fu_520_p1 = $signed(shl_ln1319_5_fu_512_p3);

assign sext_ln1319_6_fu_532_p1 = $signed(shl_ln1319_6_fu_524_p3);

assign sext_ln1319_7_fu_596_p1 = $signed(shl_ln1319_7_fu_588_p3);

assign sext_ln1319_8_fu_632_p1 = $signed(shl_ln1319_8_fu_624_p3);

assign sext_ln1319_9_fu_668_p1 = $signed(shl_ln1319_9_fu_660_p3);

assign sext_ln1319_fu_310_p1 = $signed(shl_ln_fu_302_p3);

assign sext_ln17_1_fu_1008_p1 = $signed(mult_V_20_fu_998_p4);

assign sext_ln17_2_fu_360_p1 = $signed(mult_V_1_fu_350_p4);

assign sext_ln17_3_fu_392_p1 = $signed(mult_V_2_fu_382_p4);

assign sext_ln17_4_fu_434_p1 = $signed(mult_V_3_fu_424_p4);

assign sext_ln17_5_fu_476_p1 = $signed(mult_V_4_fu_466_p4);

assign sext_ln17_6_fu_1080_p1 = $signed(mult_V_22_fu_1070_p4);

assign sext_ln17_7_fu_1122_p1 = $signed(mult_V_23_fu_1112_p4);

assign sext_ln17_fu_566_p1 = $signed(mult_V_7_fu_556_p4);

assign sext_ln70_10_fu_882_p0 = p_read17;

assign sext_ln70_10_fu_882_p1 = sext_ln70_10_fu_882_p0;

assign sext_ln70_11_fu_918_p0 = p_read18;

assign sext_ln70_11_fu_918_p1 = sext_ln70_11_fu_918_p0;

assign sext_ln70_12_fu_1012_p0 = p_read21;

assign sext_ln70_12_fu_1012_p1 = sext_ln70_12_fu_1012_p0;

assign sext_ln70_13_fu_1048_p0 = p_read22;

assign sext_ln70_13_fu_1048_p1 = sext_ln70_13_fu_1048_p0;

assign sext_ln70_14_fu_1084_p0 = p_read23;

assign sext_ln70_14_fu_1084_p1 = sext_ln70_14_fu_1084_p0;

assign sext_ln70_15_fu_1202_p0 = p_read26;

assign sext_ln70_15_fu_1202_p1 = sext_ln70_15_fu_1202_p0;

assign sext_ln70_16_fu_1238_p0 = p_read27;

assign sext_ln70_16_fu_1238_p1 = sext_ln70_16_fu_1238_p0;

assign sext_ln70_1_fu_340_p1 = $signed(p_read1);

assign sext_ln70_2_fu_396_p0 = p_read3;

assign sext_ln70_2_fu_396_p1 = sext_ln70_2_fu_396_p0;

assign sext_ln70_3_fu_438_p0 = p_read4;

assign sext_ln70_3_fu_438_p1 = sext_ln70_3_fu_438_p0;

assign sext_ln70_4_fu_584_p0 = p_read9;

assign sext_ln70_4_fu_584_p1 = sext_ln70_4_fu_584_p0;

assign sext_ln70_5_fu_620_p0 = p_read10;

assign sext_ln70_5_fu_620_p1 = sext_ln70_5_fu_620_p0;

assign sext_ln70_6_fu_656_p0 = p_read11;

assign sext_ln70_6_fu_656_p1 = sext_ln70_6_fu_656_p0;

assign sext_ln70_7_fu_768_p0 = p_read14;

assign sext_ln70_7_fu_768_p1 = sext_ln70_7_fu_768_p0;

assign sext_ln70_8_fu_810_p0 = p_read15;

assign sext_ln70_8_fu_810_p1 = sext_ln70_8_fu_810_p0;

assign sext_ln70_9_fu_846_p0 = p_read16;

assign sext_ln70_9_fu_846_p1 = sext_ln70_9_fu_846_p0;

assign sext_ln70_fu_298_p0 = p_read;

assign sext_ln70_fu_298_p1 = sext_ln70_fu_298_p0;

assign sext_ln859_1_fu_1324_p1 = $signed(add_ln859_fu_1318_p2);

assign sext_ln859_2_fu_1340_p1 = $signed(add_ln859_2_fu_1334_p2);

assign sext_ln859_3_fu_1428_p1 = $signed(add_ln859_16_fu_1422_p2);

assign sext_ln859_fu_1474_p1 = $signed(add_ln859_23_fu_1468_p2);

assign sext_ln864_10_fu_842_p1 = $signed(mult_V_15_fu_832_p4);

assign sext_ln864_11_fu_878_p1 = $signed(mult_V_16_fu_868_p4);

assign sext_ln864_12_fu_914_p1 = $signed(mult_V_17_fu_904_p4);

assign sext_ln864_13_fu_950_p1 = $signed(mult_V_18_fu_940_p4);

assign sext_ln864_14_fu_994_p1 = $signed(mult_V_19_fu_984_p4);

assign sext_ln864_15_fu_1044_p1 = $signed(mult_V_21_fu_1034_p4);

assign sext_ln864_16_fu_1154_p1 = $signed(mult_V_24_fu_1144_p4);

assign sext_ln864_17_fu_1198_p1 = $signed(mult_V_25_fu_1188_p4);

assign sext_ln864_18_fu_1234_p1 = $signed(mult_V_26_fu_1224_p4);

assign sext_ln864_19_fu_1270_p1 = $signed(mult_V_27_fu_1260_p4);

assign sext_ln864_1_fu_336_p1 = $signed(mult_V_fu_326_p4);

assign sext_ln864_20_fu_1314_p1 = $signed(mult_V_28_fu_1304_p4);

assign sext_ln864_2_fu_508_p1 = $signed(mult_V_5_fu_498_p4);

assign sext_ln864_3_fu_552_p1 = $signed(mult_V_6_fu_542_p4);

assign sext_ln864_4_fu_616_p1 = $signed(mult_V_9_fu_606_p4);

assign sext_ln864_5_fu_652_p1 = $signed(mult_V_10_fu_642_p4);

assign sext_ln864_6_fu_688_p1 = $signed(mult_V_11_fu_678_p4);

assign sext_ln864_7_fu_720_p1 = $signed(mult_V_12_fu_710_p4);

assign sext_ln864_8_fu_764_p1 = $signed(mult_V_13_fu_754_p4);

assign sext_ln864_9_fu_806_p1 = $signed(mult_V_14_fu_796_p4);

assign sext_ln864_fu_580_p1 = $signed(mult_V_8_fu_570_p4);

assign shl_ln1319_10_fu_724_p3 = {{p_read13}, {3'd0}};

assign shl_ln1319_11_fu_736_p3 = {{p_read13}, {1'd0}};

assign shl_ln1319_12_fu_772_p1 = p_read14;

assign shl_ln1319_12_fu_772_p3 = {{shl_ln1319_12_fu_772_p1}, {2'd0}};

assign shl_ln1319_13_fu_814_p1 = p_read15;

assign shl_ln1319_13_fu_814_p3 = {{shl_ln1319_13_fu_814_p1}, {3'd0}};

assign shl_ln1319_14_fu_850_p1 = p_read16;

assign shl_ln1319_14_fu_850_p3 = {{shl_ln1319_14_fu_850_p1}, {2'd0}};

assign shl_ln1319_15_fu_886_p1 = p_read17;

assign shl_ln1319_15_fu_886_p3 = {{shl_ln1319_15_fu_886_p1}, {3'd0}};

assign shl_ln1319_16_fu_922_p1 = p_read18;

assign shl_ln1319_16_fu_922_p3 = {{shl_ln1319_16_fu_922_p1}, {2'd0}};

assign shl_ln1319_17_fu_954_p3 = {{p_read19}, {3'd0}};

assign shl_ln1319_18_fu_966_p3 = {{p_read19}, {1'd0}};

assign shl_ln1319_19_fu_1016_p1 = p_read21;

assign shl_ln1319_19_fu_1016_p3 = {{shl_ln1319_19_fu_1016_p1}, {3'd0}};

assign shl_ln1319_1_fu_364_p3 = {{p_read2}, {2'd0}};

assign shl_ln1319_20_fu_1052_p1 = p_read22;

assign shl_ln1319_20_fu_1052_p3 = {{shl_ln1319_20_fu_1052_p1}, {2'd0}};

assign shl_ln1319_21_fu_1088_p1 = p_read23;

assign shl_ln1319_21_fu_1088_p3 = {{shl_ln1319_21_fu_1088_p1}, {2'd0}};

assign shl_ln1319_22_fu_1126_p3 = {{p_read24}, {1'd0}};

assign shl_ln1319_23_fu_1158_p3 = {{p_read25}, {3'd0}};

assign shl_ln1319_24_fu_1170_p3 = {{p_read25}, {1'd0}};

assign shl_ln1319_25_fu_1206_p1 = p_read26;

assign shl_ln1319_25_fu_1206_p3 = {{shl_ln1319_25_fu_1206_p1}, {3'd0}};

assign shl_ln1319_26_fu_1242_p1 = p_read27;

assign shl_ln1319_26_fu_1242_p3 = {{shl_ln1319_26_fu_1242_p1}, {3'd0}};

assign shl_ln1319_27_fu_1274_p3 = {{p_read28}, {3'd0}};

assign shl_ln1319_28_fu_1286_p3 = {{p_read28}, {1'd0}};

assign shl_ln1319_2_fu_400_p1 = p_read3;

assign shl_ln1319_2_fu_400_p3 = {{shl_ln1319_2_fu_400_p1}, {2'd0}};

assign shl_ln1319_3_fu_442_p1 = p_read4;

assign shl_ln1319_3_fu_442_p3 = {{shl_ln1319_3_fu_442_p1}, {2'd0}};

assign shl_ln1319_4_fu_480_p3 = {{p_read5}, {1'd0}};

assign shl_ln1319_5_fu_512_p3 = {{p_read6}, {3'd0}};

assign shl_ln1319_6_fu_524_p3 = {{p_read6}, {1'd0}};

assign shl_ln1319_7_fu_588_p1 = p_read9;

assign shl_ln1319_7_fu_588_p3 = {{shl_ln1319_7_fu_588_p1}, {2'd0}};

assign shl_ln1319_8_fu_624_p1 = p_read10;

assign shl_ln1319_8_fu_624_p3 = {{shl_ln1319_8_fu_624_p1}, {3'd0}};

assign shl_ln1319_9_fu_660_p1 = p_read11;

assign shl_ln1319_9_fu_660_p3 = {{shl_ln1319_9_fu_660_p1}, {2'd0}};

assign shl_ln1319_s_fu_692_p3 = {{p_read12}, {3'd0}};

assign shl_ln_fu_302_p1 = p_read;

assign shl_ln_fu_302_p3 = {{shl_ln_fu_302_p1}, {2'd0}};

assign sub_ln1319_14_fu_784_p2 = ($signed(19'd0) - $signed(sext_ln1319_13_fu_780_p1));

assign sub_ln1319_21_fu_1100_p2 = ($signed(19'd0) - $signed(sext_ln1319_22_fu_1096_p1));

assign sub_ln1319_4_fu_412_p2 = ($signed(19'd0) - $signed(sext_ln1319_2_fu_408_p1));

assign sub_ln1319_6_fu_454_p2 = ($signed(19'd0) - $signed(sext_ln1319_3_fu_450_p1));

assign sub_ln1319_fu_314_p2 = ($signed(19'd0) - $signed(sext_ln1319_fu_310_p1));

endmodule //myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s
