-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s is
port (
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read6 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read7 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read8 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read9 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read10 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read11 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read12 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read13 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read14 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read15 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read16 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read17 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read18 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read19 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read22 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read24 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read25 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read26 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read27 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read28 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read29 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read30 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read31 : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_16 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_17 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_18 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_19 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_20 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_21 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_22 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_23 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_24 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_25 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_26 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_27 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_28 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of myproject_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal icmp_ln1695_fu_364_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_28_fu_360_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_V_fu_370_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln1695_1_fu_382_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_27_fu_356_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_V_1_fu_388_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln1695_2_fu_400_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_26_fu_352_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_V_2_fu_406_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln1695_3_fu_418_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_25_fu_348_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_V_3_fu_424_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln1695_4_fu_436_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_24_fu_344_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_V_4_fu_442_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln1695_5_fu_454_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_23_fu_340_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_V_5_fu_460_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln1695_6_fu_472_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_22_fu_336_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_V_6_fu_478_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln1695_7_fu_490_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_21_fu_332_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_V_7_fu_496_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln1695_8_fu_508_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_20_fu_328_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_V_8_fu_514_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln1695_9_fu_526_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_19_fu_324_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_V_9_fu_532_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln1695_10_fu_544_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_18_fu_320_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_V_10_fu_550_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln1695_11_fu_562_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_17_fu_316_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_V_11_fu_568_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln1695_12_fu_580_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_16_fu_312_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_V_12_fu_586_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln1695_13_fu_598_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_15_fu_308_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_V_13_fu_604_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln1695_14_fu_616_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_14_fu_304_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_V_14_fu_622_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln1695_15_fu_634_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_13_fu_300_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_V_15_fu_640_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln1695_16_fu_652_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_12_fu_296_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_V_16_fu_658_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln1695_17_fu_670_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_11_fu_292_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_V_17_fu_676_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln1695_18_fu_688_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_10_fu_288_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_V_18_fu_694_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln1695_19_fu_706_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_9_fu_284_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_V_19_fu_712_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln1695_20_fu_724_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_8_fu_280_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_V_20_fu_730_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln1695_21_fu_742_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_7_fu_276_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_V_21_fu_748_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln1695_22_fu_760_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_6_fu_272_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_V_22_fu_766_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln1695_23_fu_778_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_5_fu_268_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_V_23_fu_784_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln1695_24_fu_796_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_4_fu_264_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_V_24_fu_802_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln1695_25_fu_814_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_3_fu_260_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_V_25_fu_820_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln1695_26_fu_832_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_2_fu_256_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_V_26_fu_838_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln1695_27_fu_850_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_1_fu_252_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_V_27_fu_856_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln1695_28_fu_868_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_fu_248_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_V_28_fu_874_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln45_fu_378_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_1_fu_396_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_2_fu_414_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_3_fu_432_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_4_fu_450_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_5_fu_468_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_6_fu_486_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_7_fu_504_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_8_fu_522_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_9_fu_540_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_10_fu_558_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_11_fu_576_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_12_fu_594_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_13_fu_612_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_14_fu_630_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_15_fu_648_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_16_fu_666_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_17_fu_684_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_18_fu_702_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_19_fu_720_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_20_fu_738_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_21_fu_756_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_22_fu_774_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_23_fu_792_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_24_fu_810_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_25_fu_828_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_26_fu_846_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_27_fu_864_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_28_fu_882_p1 : STD_LOGIC_VECTOR (15 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return_0 <= zext_ln45_fu_378_p1;
    ap_return_1 <= zext_ln45_1_fu_396_p1;
    ap_return_10 <= zext_ln45_10_fu_558_p1;
    ap_return_11 <= zext_ln45_11_fu_576_p1;
    ap_return_12 <= zext_ln45_12_fu_594_p1;
    ap_return_13 <= zext_ln45_13_fu_612_p1;
    ap_return_14 <= zext_ln45_14_fu_630_p1;
    ap_return_15 <= zext_ln45_15_fu_648_p1;
    ap_return_16 <= zext_ln45_16_fu_666_p1;
    ap_return_17 <= zext_ln45_17_fu_684_p1;
    ap_return_18 <= zext_ln45_18_fu_702_p1;
    ap_return_19 <= zext_ln45_19_fu_720_p1;
    ap_return_2 <= zext_ln45_2_fu_414_p1;
    ap_return_20 <= zext_ln45_20_fu_738_p1;
    ap_return_21 <= zext_ln45_21_fu_756_p1;
    ap_return_22 <= zext_ln45_22_fu_774_p1;
    ap_return_23 <= zext_ln45_23_fu_792_p1;
    ap_return_24 <= zext_ln45_24_fu_810_p1;
    ap_return_25 <= zext_ln45_25_fu_828_p1;
    ap_return_26 <= zext_ln45_26_fu_846_p1;
    ap_return_27 <= zext_ln45_27_fu_864_p1;
    ap_return_28 <= zext_ln45_28_fu_882_p1;
    ap_return_3 <= zext_ln45_3_fu_432_p1;
    ap_return_4 <= zext_ln45_4_fu_450_p1;
    ap_return_5 <= zext_ln45_5_fu_468_p1;
    ap_return_6 <= zext_ln45_6_fu_486_p1;
    ap_return_7 <= zext_ln45_7_fu_504_p1;
    ap_return_8 <= zext_ln45_8_fu_522_p1;
    ap_return_9 <= zext_ln45_9_fu_540_p1;
    datareg_V_10_fu_550_p3 <= 
        trunc_ln40_18_fu_320_p1 when (icmp_ln1695_10_fu_544_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_V_11_fu_568_p3 <= 
        trunc_ln40_17_fu_316_p1 when (icmp_ln1695_11_fu_562_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_V_12_fu_586_p3 <= 
        trunc_ln40_16_fu_312_p1 when (icmp_ln1695_12_fu_580_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_V_13_fu_604_p3 <= 
        trunc_ln40_15_fu_308_p1 when (icmp_ln1695_13_fu_598_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_V_14_fu_622_p3 <= 
        trunc_ln40_14_fu_304_p1 when (icmp_ln1695_14_fu_616_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_V_15_fu_640_p3 <= 
        trunc_ln40_13_fu_300_p1 when (icmp_ln1695_15_fu_634_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_V_16_fu_658_p3 <= 
        trunc_ln40_12_fu_296_p1 when (icmp_ln1695_16_fu_652_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_V_17_fu_676_p3 <= 
        trunc_ln40_11_fu_292_p1 when (icmp_ln1695_17_fu_670_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_V_18_fu_694_p3 <= 
        trunc_ln40_10_fu_288_p1 when (icmp_ln1695_18_fu_688_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_V_19_fu_712_p3 <= 
        trunc_ln40_9_fu_284_p1 when (icmp_ln1695_19_fu_706_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_V_1_fu_388_p3 <= 
        trunc_ln40_27_fu_356_p1 when (icmp_ln1695_1_fu_382_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_V_20_fu_730_p3 <= 
        trunc_ln40_8_fu_280_p1 when (icmp_ln1695_20_fu_724_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_V_21_fu_748_p3 <= 
        trunc_ln40_7_fu_276_p1 when (icmp_ln1695_21_fu_742_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_V_22_fu_766_p3 <= 
        trunc_ln40_6_fu_272_p1 when (icmp_ln1695_22_fu_760_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_V_23_fu_784_p3 <= 
        trunc_ln40_5_fu_268_p1 when (icmp_ln1695_23_fu_778_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_V_24_fu_802_p3 <= 
        trunc_ln40_4_fu_264_p1 when (icmp_ln1695_24_fu_796_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_V_25_fu_820_p3 <= 
        trunc_ln40_3_fu_260_p1 when (icmp_ln1695_25_fu_814_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_V_26_fu_838_p3 <= 
        trunc_ln40_2_fu_256_p1 when (icmp_ln1695_26_fu_832_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_V_27_fu_856_p3 <= 
        trunc_ln40_1_fu_252_p1 when (icmp_ln1695_27_fu_850_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_V_28_fu_874_p3 <= 
        trunc_ln40_fu_248_p1 when (icmp_ln1695_28_fu_868_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_V_2_fu_406_p3 <= 
        trunc_ln40_26_fu_352_p1 when (icmp_ln1695_2_fu_400_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_V_3_fu_424_p3 <= 
        trunc_ln40_25_fu_348_p1 when (icmp_ln1695_3_fu_418_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_V_4_fu_442_p3 <= 
        trunc_ln40_24_fu_344_p1 when (icmp_ln1695_4_fu_436_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_V_5_fu_460_p3 <= 
        trunc_ln40_23_fu_340_p1 when (icmp_ln1695_5_fu_454_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_V_6_fu_478_p3 <= 
        trunc_ln40_22_fu_336_p1 when (icmp_ln1695_6_fu_472_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_V_7_fu_496_p3 <= 
        trunc_ln40_21_fu_332_p1 when (icmp_ln1695_7_fu_490_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_V_8_fu_514_p3 <= 
        trunc_ln40_20_fu_328_p1 when (icmp_ln1695_8_fu_508_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_V_9_fu_532_p3 <= 
        trunc_ln40_19_fu_324_p1 when (icmp_ln1695_9_fu_526_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_V_fu_370_p3 <= 
        trunc_ln40_28_fu_360_p1 when (icmp_ln1695_fu_364_p2(0) = '1') else 
        ap_const_lv15_0;
    icmp_ln1695_10_fu_544_p2 <= "1" when (signed(p_read10) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1695_11_fu_562_p2 <= "1" when (signed(p_read11) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1695_12_fu_580_p2 <= "1" when (signed(p_read12) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1695_13_fu_598_p2 <= "1" when (signed(p_read13) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1695_14_fu_616_p2 <= "1" when (signed(p_read14) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1695_15_fu_634_p2 <= "1" when (signed(p_read15) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1695_16_fu_652_p2 <= "1" when (signed(p_read16) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1695_17_fu_670_p2 <= "1" when (signed(p_read17) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1695_18_fu_688_p2 <= "1" when (signed(p_read18) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1695_19_fu_706_p2 <= "1" when (signed(p_read19) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1695_1_fu_382_p2 <= "1" when (signed(p_read1) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1695_20_fu_724_p2 <= "1" when (signed(p_read22) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1695_21_fu_742_p2 <= "1" when (signed(p_read24) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1695_22_fu_760_p2 <= "1" when (signed(p_read25) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1695_23_fu_778_p2 <= "1" when (signed(p_read26) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1695_24_fu_796_p2 <= "1" when (signed(p_read27) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1695_25_fu_814_p2 <= "1" when (signed(p_read28) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1695_26_fu_832_p2 <= "1" when (signed(p_read29) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1695_27_fu_850_p2 <= "1" when (signed(p_read30) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1695_28_fu_868_p2 <= "1" when (signed(p_read31) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1695_2_fu_400_p2 <= "1" when (signed(p_read2) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1695_3_fu_418_p2 <= "1" when (signed(p_read3) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1695_4_fu_436_p2 <= "1" when (signed(p_read4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1695_5_fu_454_p2 <= "1" when (signed(p_read5) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1695_6_fu_472_p2 <= "1" when (signed(p_read6) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1695_7_fu_490_p2 <= "1" when (signed(p_read7) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1695_8_fu_508_p2 <= "1" when (signed(p_read8) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1695_9_fu_526_p2 <= "1" when (signed(p_read9) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1695_fu_364_p2 <= "1" when (signed(p_read) > signed(ap_const_lv16_0)) else "0";
    trunc_ln40_10_fu_288_p1 <= p_read18(15 - 1 downto 0);
    trunc_ln40_11_fu_292_p1 <= p_read17(15 - 1 downto 0);
    trunc_ln40_12_fu_296_p1 <= p_read16(15 - 1 downto 0);
    trunc_ln40_13_fu_300_p1 <= p_read15(15 - 1 downto 0);
    trunc_ln40_14_fu_304_p1 <= p_read14(15 - 1 downto 0);
    trunc_ln40_15_fu_308_p1 <= p_read13(15 - 1 downto 0);
    trunc_ln40_16_fu_312_p1 <= p_read12(15 - 1 downto 0);
    trunc_ln40_17_fu_316_p1 <= p_read11(15 - 1 downto 0);
    trunc_ln40_18_fu_320_p1 <= p_read10(15 - 1 downto 0);
    trunc_ln40_19_fu_324_p1 <= p_read9(15 - 1 downto 0);
    trunc_ln40_1_fu_252_p1 <= p_read30(15 - 1 downto 0);
    trunc_ln40_20_fu_328_p1 <= p_read8(15 - 1 downto 0);
    trunc_ln40_21_fu_332_p1 <= p_read7(15 - 1 downto 0);
    trunc_ln40_22_fu_336_p1 <= p_read6(15 - 1 downto 0);
    trunc_ln40_23_fu_340_p1 <= p_read5(15 - 1 downto 0);
    trunc_ln40_24_fu_344_p1 <= p_read4(15 - 1 downto 0);
    trunc_ln40_25_fu_348_p1 <= p_read3(15 - 1 downto 0);
    trunc_ln40_26_fu_352_p1 <= p_read2(15 - 1 downto 0);
    trunc_ln40_27_fu_356_p1 <= p_read1(15 - 1 downto 0);
    trunc_ln40_28_fu_360_p1 <= p_read(15 - 1 downto 0);
    trunc_ln40_2_fu_256_p1 <= p_read29(15 - 1 downto 0);
    trunc_ln40_3_fu_260_p1 <= p_read28(15 - 1 downto 0);
    trunc_ln40_4_fu_264_p1 <= p_read27(15 - 1 downto 0);
    trunc_ln40_5_fu_268_p1 <= p_read26(15 - 1 downto 0);
    trunc_ln40_6_fu_272_p1 <= p_read25(15 - 1 downto 0);
    trunc_ln40_7_fu_276_p1 <= p_read24(15 - 1 downto 0);
    trunc_ln40_8_fu_280_p1 <= p_read22(15 - 1 downto 0);
    trunc_ln40_9_fu_284_p1 <= p_read19(15 - 1 downto 0);
    trunc_ln40_fu_248_p1 <= p_read31(15 - 1 downto 0);
    zext_ln45_10_fu_558_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_10_fu_550_p3),16));
    zext_ln45_11_fu_576_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_11_fu_568_p3),16));
    zext_ln45_12_fu_594_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_12_fu_586_p3),16));
    zext_ln45_13_fu_612_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_13_fu_604_p3),16));
    zext_ln45_14_fu_630_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_14_fu_622_p3),16));
    zext_ln45_15_fu_648_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_15_fu_640_p3),16));
    zext_ln45_16_fu_666_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_16_fu_658_p3),16));
    zext_ln45_17_fu_684_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_17_fu_676_p3),16));
    zext_ln45_18_fu_702_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_18_fu_694_p3),16));
    zext_ln45_19_fu_720_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_19_fu_712_p3),16));
    zext_ln45_1_fu_396_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_1_fu_388_p3),16));
    zext_ln45_20_fu_738_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_20_fu_730_p3),16));
    zext_ln45_21_fu_756_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_21_fu_748_p3),16));
    zext_ln45_22_fu_774_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_22_fu_766_p3),16));
    zext_ln45_23_fu_792_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_23_fu_784_p3),16));
    zext_ln45_24_fu_810_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_24_fu_802_p3),16));
    zext_ln45_25_fu_828_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_25_fu_820_p3),16));
    zext_ln45_26_fu_846_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_26_fu_838_p3),16));
    zext_ln45_27_fu_864_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_27_fu_856_p3),16));
    zext_ln45_28_fu_882_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_28_fu_874_p3),16));
    zext_ln45_2_fu_414_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_2_fu_406_p3),16));
    zext_ln45_3_fu_432_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_3_fu_424_p3),16));
    zext_ln45_4_fu_450_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_4_fu_442_p3),16));
    zext_ln45_5_fu_468_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_5_fu_460_p3),16));
    zext_ln45_6_fu_486_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_6_fu_478_p3),16));
    zext_ln45_7_fu_504_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_7_fu_496_p3),16));
    zext_ln45_8_fu_522_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_8_fu_514_p3),16));
    zext_ln45_9_fu_540_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_9_fu_532_p3),16));
    zext_ln45_fu_378_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_fu_370_p3),16));
end behav;
