Backend: Vitis
ClockPeriod: 5
ClockUncertainty: 27%
HLSConfig:
  Model:
    BramFactor: 1000000000
    Precision:
      default: ap_fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'hls4ml_prj_u55c_new/keras_model.keras'
OutputDir: hls4ml_prj_u55c_new
OutputPredictions: null
Part: xcu55c-fsvh2892-2L-e
ProjectName: myproject
Stamp: e3016338
Version: 1.0.0
WriterConfig:
  Namespace: null
  WriteTar: false
  WriteWeightsTxt: true
